# Utiliser Ubuntu comme base
FROM ubuntu:latest

# Mettre à jour APT et mettre à niveau
RUN apt-get update && apt-get upgrade -y

# Commande par défaut : afficher Hello, World!
CMD echo "Hello, World!"
